doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Shop:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Components/Shop/Entity'
                prefix: 'App\Components\Shop\Entity'
                alias: App/Components/Shop
            Player:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Components/Player/Entity'
                prefix: 'App\Components\Player\Entity'
                alias: App/Components/Player
            Task:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Components/Task/Entity'
                prefix: 'App\Components\Task\Entity'
                alias: App/Components/Task
            Category:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Components/Category/Entity'
                prefix: 'App\Components\Category\Entity'
                alias: App/Components/Category
            Statistic:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Components/Statistic/Entity'
                prefix: 'App\Components\Statistic\Entity'
                alias: App/Components/Statistic
            Challenge:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Components/Challenge/Entity'
                prefix: 'App\Components\Challenge\Entity'
                alias: App/Components/Challenge
            Achievement:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Components/Achievement/Entity'
                prefix: 'App\Components\Achievement\Entity'
                alias: App/Components/Achievement
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
