lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # path to the private key
    public_key: '%kernel.project_dir%/config/jwt/public.pem'  # path to the public key
    pass_phrase: '%env(JWT_PASSPHRASE)%' # optional, if you set a passphrase when you generated the keys
    token_ttl: 3600
