version: '3.7'

services:
  php:
    container_name: symfony_php
    build:
      context: .
      target: app_php_dev
    depends_on:
      - mysql
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=EDITME
      - DATABASE_URL=mysql://task:password@mysql/task?serverVersion=8.0.32&charset=utf8mb4
      - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
      - SENTRY_DSN=https://76fa7942e6a970ea854a4300bd0b0066@o927425.ingest.us.sentry.io/4508624291889152
    volumes:
      - .:/srv/app:rw,cached
      # if you develop on Linux, you may use a bind-mounted host directory instead
      - ./var:/srv/app/var:rw
      #      - ./public:/srv/open_marketplace/public:rw,delegated
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./public/media:/srv/open_marketplace/public/media:rw
      - public-media:/srv/app/public/media:rw

  mysql:
    image: mysql:8.0 # Sylius is fully working on mysql 8.0 version
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=task
      - MYSQL_USER=task
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/mysql/data:/var/lib/mysql:rw,delegated
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE # prevent "mbind: Operation not permitted" errors

  nginx:
    container_name: symfony_nginx
    build:
      context: .
      target: app_nginx
    depends_on:
      - php
    volumes:
      - ./public:/srv/app/public:ro
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./public/media:/srv/open_marketplace/public/media:ro
      - public-media:/srv/app/public/media:ro,nocopy
    ports:
      - "${HTTP_PORT:-80}:80"

volumes:
  mysql-data:
  public-media:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
