version: '3.7'

services:
  php:
    container_name: symfony_php
    build:
      context: .
      target: app_php_dev
    depends_on:
      - mysql
    environment:
      - MAILER_DSN=smtp://mailhog:1025
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=EDITME
      - DATABASE_URL=mysql://task:password@mysql/task?serverVersion=8.0.32&charset=utf8mb4
      - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
      - SENTRY_DSN=https://76fa7942e6a970ea854a4300bd0b0066@o927425.ingest.us.sentry.io/4508624291889152
    volumes:
      - .:/srv/app:rw,cached
      - ./var:/srv/app/var:rw
      - public-media:/srv/app/public/media:rw

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=task
      - MYSQL_USER=task
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE

  nginx:
    container_name: symfony_nginx
    build:
      context: .
      target: app_nginx
    depends_on:
      - php
    volumes:
      - ./public:/srv/app/public:ro
      - public-media:/srv/app/public/media:ro,nocopy
    ports:
      - "${HTTP_PORT:-80}:80"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql-data:
  public-media:
  database_data:
